// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVpi6T7pUlUVqNxCmonHZJTHPmAGKdiX8',
    appId: '1:1018231117589:web:9a47fbdfec70e810b3bb1c',
    messagingSenderId: '1018231117589',
    projectId: 'disastersystem-33855',
    authDomain: 'disastersystem-33855.firebaseapp.com',
    storageBucket: 'disastersystem-33855.appspot.com',
    measurementId: 'G-FGH52P768J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Uihxj5dLDpZm3OK-LjegIZBXT84d6ys',
    appId: '1:1018231117589:android:e31b5fe2123311ecb3bb1c',
    messagingSenderId: '1018231117589',
    projectId: 'disastersystem-33855',
    storageBucket: 'disastersystem-33855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbrLN_px7Nulq2NRgLHWB5SmSEZloG3s',
    appId: '1:1018231117589:ios:c282f0a4414dd778b3bb1c',
    messagingSenderId: '1018231117589',
    projectId: 'disastersystem-33855',
    storageBucket: 'disastersystem-33855.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQbrLN_px7Nulq2NRgLHWB5SmSEZloG3s',
    appId: '1:1018231117589:ios:c282f0a4414dd778b3bb1c',
    messagingSenderId: '1018231117589',
    projectId: 'disastersystem-33855',
    storageBucket: 'disastersystem-33855.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVpi6T7pUlUVqNxCmonHZJTHPmAGKdiX8',
    appId: '1:1018231117589:web:f811c2229aa97f8cb3bb1c',
    messagingSenderId: '1018231117589',
    projectId: 'disastersystem-33855',
    authDomain: 'disastersystem-33855.firebaseapp.com',
    storageBucket: 'disastersystem-33855.appspot.com',
    measurementId: 'G-KNT6S4GJBK',
  );
}
